MainApp/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'MainApp'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/',views.pizza, name='pizza'),
    path('comments/<int:pizza_id>/', views.comments, name='comments'),
]

urlpatterns += staticfiles_urlpatterns()

Pizzeria/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MainApp.urls')),
    #path('',include('users.urls')),

] #+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MainApp/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here. TABLES   
class Pizza(models.Model):
    text = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='img',blank=True,null=True)

    def __str__(self):
        return self.text

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField()


    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()


    def __str__(self):
        return self.text

MainApp/forms.py
from django import forms

from .models import Pizza, Comment

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['text']
        labels = {'text':''} 

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text':''} 
        widgets = {'text': forms.Textarea(attrs={'cols':80})} 

MainApp/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment 
from .forms import PizzaForm, CommentForm 

# Create your views here.

def index(request):
    return render(request, 'MainApp/index.html') 

def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas} 

    return render(request, 'MainApp/pizzas.html', context) 

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('pizza_id') 
    picture = pizza.picture

    #comments= pizza.comment_set.all().order_by('-date_added')

    context = {'pizza':pizza, 'toppings':toppings, 'picture':picture, 'comments':comments} 

    return render(request, 'MainApp/pizza.html', context)

def new_comment(request, pizza_id):
  
    new_comment = Pizza.objects.get(id=pizza_id)
    

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False) 
            new_comment.comment = new_comment 
            new_comment.save() 
            return redirect('MainApp:pizza', pizza_id=pizza_id)  

    context = {'form':form, 'comment':new_comment}
    return render(request, 'MainApp/new_comment.html', context)


def comments(request, pizza_id):
    if request.method == 'POST' and request.POST.get('btn1'):
        comment = request.POST.get('comment') 
        Comment.objects.create(pizza_id=pizza_id,text=comment)


    comments = Comment.objects.filter(pizza_id=pizza_id)
    post = Pizza.objects.get(id=pizza_id)

    context = {'post':post, 'comments':comments} 
    
    return render(request, 'MainApp/comments.html',context)

MainApp/templates/mainapp/base.html
<!--
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>Mohan's Pizzaria</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>


<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'MainApp:index'%}">
            Mohan's Pizzaria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'MainApp:pizzas'%}">
                        Pizzas</a>
                </li>






-->
<p>
    <a href="{% url 'MainApp:index' %}">Home</a>
    <a href="{% url 'MainApp:pizzas' %}">Pizzas</a>
</p>


{% block content %}


{% endblock content %}

MainApp/templates/mainapp/comments.html
{% extends "MainApp/base.html" %}



{% block content %} 




    <form method="POST">
        {% csrf_token %} 
        {% for c in comments %} 
        <li>
            <p> {{c.text}} </p>
        </li>
        {% empty %} 
        <li>There are no comments for this post. Be the first one to leave a comment!</li>
        {% endfor %} 
    <p><input type="text" name="comment"></p>
    <p><button type="submit" name="btn1" value=1>Submit Comment</button></p>
    
    </form>




{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %} 

{% block content %} 

<p>
    Welcome to Mohan's Pizzaria!
</p>

{% endblock content %} 

MainApp/templates/mainapp/pizza.html
{% extends "MainApp/base.html" %}

{% block content %}

<p>
    Pizza: {{ pizza }}
</p>

<ul>
    {% for t in toppings %}
    <li>
        <p> {{ t }} </p>
    </li>
    {% empty %}
    <li> There are no toppings for this pizza yet. </li>
    {% endfor %}
</ul>


{% if pizza.image %}
<img src="{{ pizza.picture.url }}">
{% endif %}




<p>
    Comments:
</p>

<!--
{% for c in comments %} 
    <a href="{% url 'MainApp:comments' pizza_id %}">{{c}}</a>
{% endfor %} 

-->

<a href="{% url 'MainApp:comments' pizza.id %}">Click to see comments</a>

<ul>
    {% for c in comments %}
    <li>
        <p> {{ c }} </p>

        {% endfor %}
    </li>
</ul>
<p>
    <img src="{{ pizza.picture.url }}">
</p>

{% endblock content %}

MainApp/templates/mainapp/pizzas.html
{% extends "MainApp/base.html" %} 

{% block content %} 

<p>  
    Click on pizzas to see toppings:
</p>

<ul>
    {% for p in pizzas %}

    <li> 
    <a href="{% url 'MainApp:pizza' p.id %}">{{ p.text }}</a> 
    </li>
    {% empty %} 
    <li>No pizzas have been added yet.</li>
    {% endfor %} 
</ul>


{% endblock content %} 